---
# postgresql role defaults
pg_version: 16
pg_port: 5432
pg_listen_addresses: localhost
pg_data_dir: "/var/lib/postgresql/{{ pg_version }}/main"
pg_config_dir: "/etc/postgresql/{{ pg_version }}/main"
pg_max_connections: 100
pg_shared_buffers: 256MB
pg_effective_cache_size: 1GB
pg_work_mem: 8MB
pg_log_min_duration_statement: 1000

pg_role: standalone
pg_wal_level: replica
pg_max_wal_senders: 4
pg_wal_keep_size: 512MB
pg_hot_standby: "on"
pg_synchronous_commit: "on"
pg_replication_user: replicator
pg_replica_hosts: []

pg_allowed_networks: []
pg_databases: []
pg_users: []

# Secrets - override from vars/secrets.yml
vault_pg_superuser_password: CHANGEME-pg-superuser
vault_pg_replication_password: CHANGEME-pg-replication
