package scanner

import (
	"path/filepath"
	"testing"

	"github.com/jgsqware/pine/internal/model"
)

// The automation-first homelab layout: hosts declare their services once,
// the service axis (docker_hosts, postgresql_hosts, ...) is generated by
// the ansible.builtin.constructed plugin from inventory/99-constructed.yml.
func TestConstructedInventory(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "inventory/00-hosts.yml"), `
prod_db:
  hosts:
    prod-db:
      ansible_host: 192.168.10.20
      services: [postgresql]
prod_app:
  hosts:
    prod-app:
      ansible_host: 192.168.10.21
      services: [docker]
management:
  hosts:
    mgnt:
      ansible_host: 192.168.1.2
      services: [docker, pihole]
`)
	writeFile(t, filepath.Join(root, "inventory/99-constructed.yml"), `
plugin: ansible.builtin.constructed
strict: false
groups:
  docker_hosts:     "'docker' in (services | default([]))"
  postgresql_hosts: "'postgresql' in (services | default([]))"
  pihole_hosts:     "'pihole' in (services | default([]))"
  backup_hosts:     "('docker' in (services|default([]))) or ('postgresql' in (services|default([])))"
`)

	res, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Inventories) != 1 {
		t.Fatalf("inventories = %d, want 1 merged (%+v)", len(res.Inventories), res.Inventories)
	}
	inv := res.Inventories[0]
	if inv.Name != "default" || inv.Path != "inventory" {
		t.Errorf("name=%q path=%q, want default/inventory", inv.Name, inv.Path)
	}

	groups := map[string]model.Group{}
	for _, g := range inv.Groups {
		groups[g.Name] = g
	}
	check := func(name string, wantHosts []string) {
		t.Helper()
		g, ok := groups[name]
		if !ok {
			t.Errorf("generated group %s missing (have %v)", name, groupNames(inv.Groups))
			return
		}
		if !g.Constructed {
			t.Errorf("%s should be marked constructed", name)
		}
		if len(g.Hosts) != len(wantHosts) {
			t.Errorf("%s hosts = %v, want %v", name, g.Hosts, wantHosts)
			return
		}
		for _, h := range wantHosts {
			if !contains(g.Hosts, h) {
				t.Errorf("%s missing host %s (got %v)", name, h, g.Hosts)
			}
		}
	}
	check("docker_hosts", []string{"prod-app", "mgnt"})
	check("postgresql_hosts", []string{"prod-db"})
	check("pihole_hosts", []string{"mgnt"})
	check("backup_hosts", []string{"prod-db", "prod-app", "mgnt"})

	// hand-written groups stay, not marked constructed
	if g, ok := groups["prod_db"]; !ok || g.Constructed {
		t.Errorf("prod_db: ok=%v constructed=%v", ok, ok && g.Constructed)
	}

	// host membership includes the generated axis
	for _, h := range inv.Hosts {
		if h.Name == "mgnt" {
			for _, want := range []string{"management", "docker_hosts", "pihole_hosts", "backup_hosts"} {
				if !contains(h.Groups, want) {
					t.Errorf("mgnt groups = %v, missing %s", h.Groups, want)
				}
			}
		}
	}
}

// Conditions can use group_vars too: effective vars = group vars + host vars.
func TestConstructedUsesGroupVars(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "inventory/00-hosts.yml"), `
prod:
  hosts:
    prod-app:
dev:
  hosts:
    dev-box:
`)
	writeFile(t, filepath.Join(root, "inventory/group_vars/prod.yml"), "env: production\n")
	writeFile(t, filepath.Join(root, "inventory/group_vars/dev.yml"), "env: development\n")
	writeFile(t, filepath.Join(root, "inventory/99-constructed.yml"), `
plugin: constructed
groups:
  monitored: "env == 'production'"
  unmonitored: "env is defined and env != 'production'"
`)
	res, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	inv := res.Inventories[0]
	got := map[string][]string{}
	for _, g := range inv.Groups {
		if g.Constructed {
			got[g.Name] = g.Hosts
		}
	}
	if len(got["monitored"]) != 1 || got["monitored"][0] != "prod-app" {
		t.Errorf("monitored = %v", got["monitored"])
	}
	if len(got["unmonitored"]) != 1 || got["unmonitored"][0] != "dev-box" {
		t.Errorf("unmonitored = %v", got["unmonitored"])
	}
}

// keyed_groups generates one group per value (lists fan out).
func TestConstructedKeyedGroups(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "inventory/00-hosts.yml"), `
all:
  hosts:
    app01:
      services: [docker, redis]
    db01:
      services: [postgresql]
`)
	writeFile(t, filepath.Join(root, "inventory/99-constructed.yml"), `
plugin: ansible.builtin.constructed
keyed_groups:
  - key: services
    prefix: svc
`)
	res, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	inv := res.Inventories[0]
	got := map[string][]string{}
	for _, g := range inv.Groups {
		if g.Constructed {
			got[g.Name] = g.Hosts
		}
	}
	if len(got["svc_docker"]) != 1 || got["svc_docker"][0] != "app01" {
		t.Errorf("svc_docker = %v", got["svc_docker"])
	}
	if len(got["svc_redis"]) != 1 {
		t.Errorf("svc_redis = %v", got["svc_redis"])
	}
	if len(got["svc_postgresql"]) != 1 || got["svc_postgresql"][0] != "db01" {
		t.Errorf("svc_postgresql = %v", got["svc_postgresql"])
	}
}

func TestEvalExpr(t *testing.T) {
	vars := map[string]any{
		"services": []any{"docker", "pihole"},
		"env":      "production",
		"count":    float64(3),
		"flag":     true,
	}
	cases := []struct {
		expr string
		want bool
	}{
		{`'docker' in (services | default([]))`, true},
		{`'postgresql' in (services | default([]))`, false},
		{`'x' in (missing | default([]))`, false},
		{`('docker' in (services|default([]))) or ('postgresql' in (services|default([])))`, true},
		{`env == 'production'`, true},
		{`env != 'production'`, false},
		{`env == 'production' and 'pihole' in services`, true},
		{`not flag`, false},
		{`missing is defined`, false},
		{`missing is not defined`, true},
		{`env is defined`, true},
		{`'docker' not in services`, false},
		{`count == 3`, true},
		{`env | lower == 'production'`, true},
		{`missing`, false},
		{`flag`, true},
	}
	for _, c := range cases {
		if got := truthy(evalExpr(c.expr, vars)); got != c.want {
			t.Errorf("evalExpr(%q) = %v, want %v", c.expr, got, c.want)
		}
	}
}

func groupNames(gs []model.Group) []string {
	var out []string
	for _, g := range gs {
		out = append(out, g.Name)
	}
	return out
}
