package scanner

import (
	"path/filepath"
	"testing"
)

// TestSidecarDescriptions verifies that a repo-root pine.yml `descriptions:`
// map is read back onto the matching playbook (keyed by repo-relative path).
func TestSidecarDescriptions(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "playbooks", "site.yml"), `---
- hosts: all
  tasks:
    - name: ping
      ansible.builtin.ping:
`)
	writeFile(t, filepath.Join(root, "pine.yml"), `# generated by Pine
descriptions:
  playbooks/site.yml: "Converge every host"
  playbooks/missing.yml: "orphan entry is harmless"
`)
	res, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	var found bool
	for _, pb := range res.Playbooks {
		if filepath.ToSlash(pb.Path) == "playbooks/site.yml" {
			found = true
			if pb.Description != "Converge every host" {
				t.Fatalf("description not applied: %q", pb.Description)
			}
		}
	}
	if !found {
		t.Fatalf("playbooks/site.yml not scanned; got %d playbooks", len(res.Playbooks))
	}
}

func TestNoSidecarIsFine(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "site.yml"), `---
- hosts: all
  tasks: []
`)
	res, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	for _, pb := range res.Playbooks {
		if pb.Description != "" {
			t.Fatalf("no sidecar should mean empty description, got %q", pb.Description)
		}
	}
}
