// Package model defines the core data types shared across Pine:
// scanned Ansible content, repositories and jobs.
package model

// Task is a single Ansible task (or block) extracted from a playbook or role.
type Task struct {
	Name        string   `json:"name"`
	Module      string   `json:"module"`
	Args        string   `json:"args,omitempty"`         // concise rendering of the module's argument(s)
	IncludePath string   `json:"include_path,omitempty"` // file referenced by an include_/import_ module
	Tags        []string `json:"tags,omitempty"`
	When        string   `json:"when,omitempty"`
	Loop        bool     `json:"loop,omitempty"`
	LoopExpr    string   `json:"loop_expr,omitempty"`    // raw loop expression, for plan-time resolution
	LoopItems   int      `json:"loop_items,omitempty"`   // literal list size known at scan time
	LoopValues  []any    `json:"loop_values,omitempty"`  // literal loop items (capped), shown instead of {{ item }}
	RoleRef     string   `json:"role_ref,omitempty"`     // role name for include_role/import_role tasks
	IncludeVars string   `json:"include_vars,omitempty"` // repo-relative path of a static include_vars file (resolved at scan time)
	Listen      string   `json:"listen,omitempty"`       // handler listen topic
	Notify      []string `json:"notify,omitempty"`
	Block       []Task   `json:"block,omitempty"`
	Rescue      []Task   `json:"rescue,omitempty"`
	Always      []Task   `json:"always,omitempty"`
	// Imported holds the tasks pulled in from a static `import_tasks: file`
	// (resolved at scan time, since import_tasks is processed statically by
	// Ansible). Empty for dynamic include_tasks or unresolvable/Jinja paths.
	Imported []Task `json:"imported,omitempty"`
}

// PromptVar is one vars_prompt entry on a play.
type PromptVar struct {
	Name    string `json:"name"`
	Prompt  string `json:"prompt,omitempty"`
	Default string `json:"default,omitempty"`
	Private bool   `json:"private,omitempty"`
}

// Play is one play inside a playbook.
type Play struct {
	Name       string         `json:"name"`
	Hosts      string         `json:"hosts"`
	Become     bool           `json:"become,omitempty"`
	Serial     string         `json:"serial,omitempty"`
	Strategy   string         `json:"strategy,omitempty"`
	Tags       []string       `json:"tags,omitempty"`
	Vars       map[string]any `json:"vars,omitempty"`
	VarsFiles  []string       `json:"vars_files,omitempty"`
	VarsPrompt []PromptVar    `json:"vars_prompt,omitempty"`
	Roles      []string       `json:"roles,omitempty"`
	PreTasks   []Task         `json:"pre_tasks,omitempty"`
	Tasks      []Task         `json:"tasks,omitempty"`
	PostTasks  []Task         `json:"post_tasks,omitempty"`
	Handlers   []Task         `json:"handlers,omitempty"`
	Import     string         `json:"import,omitempty"` // set when the entry is an import_playbook
}

// Playbook is a scanned playbook file.
type Playbook struct {
	Path  string `json:"path"`
	Name  string `json:"name"`
	Plays []Play `json:"plays"`
}

// Role is a scanned Ansible role.
type Role struct {
	Name         string         `json:"name"`
	Path         string         `json:"path"`
	Description  string         `json:"description,omitempty"`
	Dependencies []string       `json:"dependencies,omitempty"`
	TasksCount   int            `json:"tasks_count"`
	Tasks        []Task         `json:"tasks,omitempty"`
	Handlers     []Task         `json:"handlers,omitempty"`
	Defaults     map[string]any `json:"defaults,omitempty"`
	Vars         map[string]any `json:"vars,omitempty"`
	Templates    []string       `json:"templates,omitempty"`
	Files        []string       `json:"files,omitempty"`
}

// Group is an inventory group. Constructed marks groups generated by the
// ansible.builtin.constructed inventory plugin rather than declared by hand.
type Group struct {
	Name        string         `json:"name"`
	Hosts       []string       `json:"hosts"`
	Children    []string       `json:"children,omitempty"`
	Vars        map[string]any `json:"vars,omitempty"`
	Constructed bool           `json:"constructed,omitempty"`
}

// Host is an inventory host with its resolved group memberships.
type Host struct {
	Name   string         `json:"name"`
	Groups []string       `json:"groups"`
	Vars   map[string]any `json:"vars,omitempty"`
}

// ServiceState is one service's status on a host, harvested from ansible's
// service_facts module (or synthesized in simulated mode). State is the
// honest tri-state running | stopped | unknown; Status is enabled | disabled
// | unknown (boot enablement).
type ServiceState struct {
	Name   string `json:"name"`   // logical name as declared (e.g. teamcity-agent)
	Unit   string `json:"unit"`   // systemd unit reported (e.g. teamcity-agent.service)
	State  string `json:"state"`  // running | stopped | unknown
	Status string `json:"status"` // enabled | disabled | unknown
}

// Service states.
const (
	ServiceRunning = "running"
	ServiceStopped = "stopped"
	ServiceUnknown = "unknown"
)

// ConstructedRule mirrors an ansible.builtin.constructed plugin config so
// generated groups can be re-evaluated with what-if variables (plan mode).
type ConstructedRule struct {
	Groups      map[string]string `json:"groups,omitempty"`
	KeyedGroups []KeyedGroup      `json:"keyed_groups,omitempty"`
}

// KeyedGroup is one keyed_groups entry of a constructed config.
type KeyedGroup struct {
	Key       string `json:"key"`
	Prefix    string `json:"prefix,omitempty"`
	Separator string `json:"separator,omitempty"`
}

// Inventory is a scanned inventory source (directory or single file).
type Inventory struct {
	Name             string            `json:"name"`
	Path             string            `json:"path"`
	Format           string            `json:"format"` // ini | yaml
	Groups           []Group           `json:"groups"`
	Hosts            []Host            `json:"hosts"`
	ConstructedRules []ConstructedRule `json:"constructed_rules,omitempty"`
}

// ScanResult is everything Pine discovered in one repository.
type ScanResult struct {
	Playbooks   []Playbook  `json:"playbooks"`
	Roles       []Role      `json:"roles"`
	Inventories []Inventory `json:"inventories"`
}

// RepoSummary holds the headline counts shown on repo cards.
type RepoSummary struct {
	Playbooks   int `json:"playbooks"`
	Roles       int `json:"roles"`
	Inventories int `json:"inventories"`
	Hosts       int `json:"hosts"`
	Groups      int `json:"groups"`
}

// Repo statuses.
const (
	RepoNew     = "new"
	RepoSyncing = "syncing"
	RepoReady   = "ready"
	RepoError   = "error"
)

// Repo is a connected Ansible repository (git URL or local path).
// ScanPaths optionally restricts playbook discovery to specific
// directories, files or glob patterns relative to the repo root.
type Repo struct {
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	URL        string      `json:"url,omitempty"`
	Path       string      `json:"path,omitempty"`
	Branch     string      `json:"branch,omitempty"`
	ScanPaths  []string    `json:"scan_paths,omitempty"`
	Status     string      `json:"status"`
	Error      string      `json:"error,omitempty"`
	LastSynced string      `json:"last_synced,omitempty"`
	Summary    RepoSummary `json:"summary"`
}

// JobSummary aggregates the PLAY RECAP counters across hosts.
type JobSummary struct {
	OK          int `json:"ok"`
	Changed     int `json:"changed"`
	Failed      int `json:"failed"`
	Skipped     int `json:"skipped"`
	Unreachable int `json:"unreachable"`
}

// Job statuses.
const (
	JobPending  = "pending"
	JobRunning  = "running"
	JobSuccess  = "success"
	JobFailed   = "failed"
	JobCanceled = "canceled"
)

// TaskDuration is the measured wall time of one task in a job run.
type TaskDuration struct {
	Task string `json:"task"`
	MS   int64  `json:"ms"`
}

// Job is one playbook execution.
type Job struct {
	ID            string         `json:"id"`
	RepoID        string         `json:"repo_id"`
	RepoName      string         `json:"repo_name"`
	Playbook      string         `json:"playbook"`
	Inventory     string         `json:"inventory,omitempty"`
	Limit         string         `json:"limit,omitempty"`
	Tags          string         `json:"tags,omitempty"`
	Check         bool           `json:"check"`
	Simulated     bool           `json:"simulated"`
	Status        string         `json:"status"`
	Created       string         `json:"created"`
	Started       string         `json:"started,omitempty"`
	Finished      string         `json:"finished,omitempty"`
	DurationMS    int64          `json:"duration_ms"`
	Summary       JobSummary     `json:"summary"`
	TaskDurations []TaskDuration `json:"task_durations,omitempty"`
}

// Terminal reports whether the job reached a final state.
func (j *Job) Terminal() bool {
	return j.Status == JobSuccess || j.Status == JobFailed || j.Status == JobCanceled
}

// Schedule is a recurring playbook run, optionally plan-gated: when Gate is
// set, the run is blocked whenever the current plan fingerprint differs
// from the approved one.
type Schedule struct {
	ID                  string `json:"id"`
	RepoID              string `json:"repo_id"`
	RepoName            string `json:"repo_name"`
	Playbook            string `json:"playbook"`
	Inventory           string `json:"inventory,omitempty"`
	Limit               string `json:"limit,omitempty"`
	Tags                string `json:"tags,omitempty"`
	Check               bool   `json:"check"`
	Interval            string `json:"interval"`
	Gate                bool   `json:"gate"`
	Enabled             bool   `json:"enabled"`
	Status              string `json:"status"` // ok | blocked | disabled
	BlockedReason       string `json:"blocked_reason,omitempty"`
	ApprovedFingerprint string `json:"approved_fingerprint,omitempty"`
	ApprovedAt          string `json:"approved_at,omitempty"`
	LastRunID           string `json:"last_run_id,omitempty"`
	LastRunAt           string `json:"last_run_at,omitempty"`
	NextRunAt           string `json:"next_run_at,omitempty"`
}

// PipelineStep is one stage of a light pipeline.
type PipelineStep struct {
	Name              string `json:"name"`
	Playbook          string `json:"playbook"`
	Inventory         string `json:"inventory,omitempty"`
	Limit             string `json:"limit,omitempty"`
	Tags              string `json:"tags,omitempty"`
	Check             bool   `json:"check"`
	RequireApproval   bool   `json:"require_approval"`
	ContinueOnFailure bool   `json:"continue_on_failure"`
}

// Pipeline chains playbooks with failure stops and approval gates.
type Pipeline struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	RepoID   string         `json:"repo_id"`
	RepoName string         `json:"repo_name"`
	Steps    []PipelineStep `json:"steps"`
}

// Pipeline run statuses (steps reuse job-like statuses plus these).
const (
	PipeRunning  = "running"
	PipeWaiting  = "waiting_approval"
	PipeSuccess  = "success"
	PipeFailed   = "failed"
	PipeCanceled = "canceled"
)

// PipelineRunStep is the live state of one step in a run.
type PipelineRunStep struct {
	Name   string `json:"name"`
	Status string `json:"status"` // pending|running|waiting_approval|success|failed|skipped|canceled
	JobID  string `json:"job_id,omitempty"`
}

// PipelineRun is one execution of a pipeline.
type PipelineRun struct {
	ID           string            `json:"id"`
	PipelineID   string            `json:"pipeline_id"`
	PipelineName string            `json:"pipeline_name"`
	Status       string            `json:"status"`
	Created      string            `json:"created"`
	Finished     string            `json:"finished,omitempty"`
	Steps        []PipelineRunStep `json:"steps"`
}
