---
# redis role defaults
redis_port: 6379
redis_bind_address: 0.0.0.0
redis_maxmemory: 512mb
redis_maxmemory_policy: allkeys-lru
redis_appendonly: "yes"
redis_databases: 16
redis_tcp_backlog: 511
redis_timeout: 300
redis_config_path: /etc/redis/redis.conf
redis_service_name: redis-server

# Secret - override from vars/secrets.yml
vault_redis_password: CHANGEME-redis
